use_frameworks!

target 'upraxis_ios_extensions_Example' do
  pod 'upraxis_ios_extensions', :path => '../'

  target 'upraxis_ios_extensions_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
